/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface DatabaseFirewallRules {
  create_date: Date;
  end_ip_address: string;
  id: Generated<number>;
  modify_date: Date;
  name: unknown;
  start_ip_address: string;
}

export interface SalesTransTemp {
  AF: string | null;
  afID: number;
  AFRate: number;
  ApprovedBy: string | null;
  Block: string;
  BR: string | null;
  brID: number;
  BRRate: number;
  BuyersAddress: string | null;
  BuyersName: string | null;
  BuyersOccupation: string | null;
  CertifiedBy: string | null;
  ContactNumber: string | null;
  DateFiled: Date | null;
  DivisionID: number;
  DivisionName: string | null;
  DownPayment: number;
  DPStartSchedule: Date | null;
  DPTerms: string;
  FinancingScheme: string;
  FloorArea: number;
  LastUpdate: Date;
  LastUpdateby: number;
  Lot: string;
  LotArea: number;
  MiscFee: number;
  MonthlyDP: number;
  NetTotalTCP: number;
  OTH: string;
  othID: number;
  OTHRate: number;
  Phase: string;
  PreparedBy: string | null;
  ProjectDeveloper: string;
  ProjectLocation: string | null;
  ProjectName: string;
  ReservationDate: Date;
  RF: string;
  rfID: number;
  RFRate: number;
  SA: string | null;
  saID: number;
  SalesStatus: number;
  SalesTranCode: string;
  SalesTranID: number;
  SARate: number;
  SD: string | null;
  sdID: number;
  SDRate: number;
  SP: string | null;
  spID: number;
  SPRate: number;
}

export interface TblAgentEducation {
  AgentEducationID: Generated<number>;
  AgentID: number | null;
  AgentRegistrationID: number | null;
  Degree: string;
  EndDate: Date | null;
  School: string;
  StartDate: Date;
}

export interface TblAgentPendingSales {
  AgentPendingSalesID: Generated<number>;
  ApprovalStatus: Generated<number>;
  ApprovedSalesTranID: number | null;
  Block: string;
  BuyersAddress: string | null;
  BuyersContactNumber: string | null;
  BuyersName: string | null;
  BuyersOccupation: string | null;
  CommStatus: string | null;
  CreatedBy: number;
  DateFiled: Date | null;
  DevCommType: string;
  DeveloperID: number | null;
  DivisionID: number | null;
  DownPayment: number;
  DPStartSchedule: Date | null;
  DPTerms: string;
  FinancingScheme: string;
  FloorArea: number;
  LastUpdate: Date;
  LastUpdateby: number;
  Lot: string;
  LotArea: number;
  MiscFee: number;
  MonthlyDP: number;
  NetTotalTCP: number;
  PendingSalesTranCode: string;
  Phase: string;
  ProjectID: number | null;
  ProjectLocationID: number | null;
  Remarks: string | null;
  ReservationDate: Date;
  SalesBranchID: number | null;
  SalesSectorID: number;
  SalesStatus: string;
  SellerName: string;
}

export interface TblAgentPendingSalesDtl {
  AgentID: number;
  AgentName: string | null;
  AgentPendingSalesDtlID: Generated<number>;
  Commission: number;
  CommissionRate: number;
  PendingSalesTranCode: string;
  PositionID: number;
  PositionName: string;
  VATRate: number;
  WTaxRate: number;
}

export interface TblAgentReferral {
  AgentID: number;
  LastUpdate: Date;
  ReferralID: number;
  ReferredByID: number;
  Updateby: number;
}

export interface TblAgentRegistration {
  Address: string;
  AddressEmergency: string;
  AffiliationDate: Date;
  AgentCode: string;
  AgentRegistrationID: Generated<number>;
  AgentTaxRate: number;
  Birthdate: Date;
  Birthplace: string | null;
  CivilStatus: string;
  ContactEmergency: string;
  ContactNumber: string;
  DivisionID: string | null;
  DSHUDNumber: string | null;
  EmployeeIDNumber: string | null;
  FirstName: string;
  IsVerified: Generated<number>;
  LastName: string;
  LastUpdate: Generated<Date>;
  MiddleName: string;
  PagIbigNumber: string | null;
  PersonEmergency: string;
  PhilhealthNumber: string | null;
  PositionID: number | null;
  PRCNumber: string | null;
  ReferredByID: number | null;
  ReferredCode: string | null;
  Religion: string | null;
  Sex: string;
  SSSNumber: string | null;
  TelephoneNumber: string | null;
  TINNumber: string | null;
  UpdateBy: number | null;
}

export interface TblAgents {
  Address: string;
  AddressEmergency: string;
  AffiliationDate: Date;
  AgentCode: string;
  AgentID: Generated<number>;
  AgentTaxRate: number;
  Birthdate: Date;
  Birthplace: string | null;
  CivilStatus: string;
  ContactEmergency: string;
  ContactNumber: string;
  DivisionID: string | null;
  DSHUDNumber: string | null;
  EmployeeIDNumber: string | null;
  FirstName: string;
  IsActive: number;
  LastName: string;
  LastUpdate: Date;
  MiddleName: string;
  PagIbigNumber: string | null;
  PersonEmergency: string;
  PhilhealthNumber: string | null;
  PositionID: number | null;
  PRCNumber: string | null;
  ReferredByID: number | null;
  ReferredCode: string | null;
  Religion: string | null;
  Sex: string;
  SSSNumber: string | null;
  TelephoneNumber: string | null;
  TINNumber: string | null;
  UpdateBy: number;
}

export interface TblAgentSession {
  AgentUserID: number;
  ExpiresAt: Date;
  SessionID: Generated<number>;
  SessionString: string;
}

export interface TblAgentsold {
  Address: string;
  AddressEmergency: string;
  AgentCode: string;
  AgentID: number;
  AgentTaxRate: number;
  Birthdate: Date;
  CivilStatus: string;
  ContactEmergency: string;
  ContactNumber: string;
  DivisionID: string | null;
  DSHUDNumber: string | null;
  FirstName: string;
  IsActive: number;
  LastName: string;
  LastUpdate: Date;
  MiddleName: string;
  PersonEmergency: string;
  PositionID: number | null;
  PRCNumber: string | null;
  ReferredByID: number | null;
  ReferredCode: string | null;
  Sex: string;
  UpdateBy: number;
}

export interface TblAgentTaxRates {
  AgentTaxRateCode: string;
  AgentTaxRateID: number;
  AgentTaxRateName: string;
  LastUpdate: Date;
  UpdateBy: number;
  VATRate: number;
  WtaxRAte: number;
}

export interface TblAgentUser {
  AgentID: number | null;
  AgentRegistrationID: number | null;
  AgentUserID: Generated<number>;
  Email: string;
  ImageID: number | null;
  IsVerified: Generated<number>;
  Password: string;
}

export interface TblAgentWorkExp {
  AgentID: number | null;
  AgentRegistrationID: number | null;
  AgentWorkExpID: Generated<number>;
  Company: string;
  EndDate: Date;
  JobTitle: string;
  StartDate: Date;
}

export interface TblBranchDivision {
  BranchDivisionID: number;
  BranchID: number;
  DivisionID: number;
}

export interface TblBroker {
  Broker: string;
  BrokerCode: string;
  BrokerID: number;
  IsActive: number;
  LastUpdate: Date;
  RepresentativeName: string;
  UpdateBy: number;
}

export interface TblBuyers {
  Address: string;
  BuyersCode: string;
  BuyersID: number;
  BuyersName: string;
  ContactNumber: string;
  LastUpdate: Date;
  Occupation: string;
  UpdateBy: number;
}

export interface TblCashIncentive {
  CashIncentiveCode: string;
  CashIncentiveID: number;
  IncentiveType: string;
  IsActive: number;
  LastUpdate: Date;
  PeriodFrom: Date;
  PeriodTo: Date;
  UpdateBy: number;
}

export interface TblCashIncentiveDtl {
  AdditionalIncentive: number;
  AdditionalSalesIncentive: number;
  AdditionalSalesVolume: number;
  CashIncentiveCode: string;
  CashIncentiveDtlID: number;
  Incentive: number;
  MinimumSales: number;
  Position: string;
  SalesVolume: number;
}

export interface TblChartOfAccounts {
  AccountID: number;
  AccountName: string;
  AcountCode: string;
  IsDeleted: number;
  LastUpdate: Date;
  UpdateBy: number;
}

export interface TblCommCollection {
  ARDeduction: number;
  CollectionAmount: number;
  CollectionDate: Date;
  CollectionRefNumber: string;
  CommCollectionID: Generated<number>;
  DeveloperCV: string;
  DeveloperCVDate: Date;
  DeveloperID: number;
  LastUpdate: Generated<Date>;
  NetCollectionAmount: number;
  UpdateBy: Generated<number>;
  WtaxDeduction: number;
}

export interface TblCommCollectionDtl {
  ACDeduction: number;
  AdvanceCommission: number;
  BuyerName: string;
  CollectionRefNumber: string;
  CommCollectionDtlID: Generated<number>;
  CommRelRefNo: Generated<string>;
  ContractPrice: number;
  GrossAmount: number;
  Incentive: number;
  InputVAT: string;
  NetAmount: number;
  OtherDeduction: number;
  Property: string;
  ReleaseAmount: number;
  ReservationDate: Date;
  SalesNumber: string;
  WithholdingTax: number;
  WithSalesRecord: number;
}

export interface TblCommDeductionDetail {
  BuyersName: string;
  CommDedDetailID: Generated<number>;
  CommReleaseDate: Date;
  CommReleaseNo: string;
  DeductionNumber: string | null;
  GrossCommission: number;
  NetReleased: number;
  PercentReleased: number;
  PrevReleased: number;
  Property: string;
  RealtorName: string | null;
  VATAmount: number;
  WTaxAmount: number;
}

export interface TblCommDeductionSummary {
  AgentID: number;
  AgentName: string;
  CA: number;
  CommDedHeaderID: Generated<number>;
  CommDeductionDate: Date;
  CommissionRefNumber: Generated<string>;
  CommissionStatus: Generated<string>;
  CPD: number;
  DeductionNumber: string;
  DeductionType: number;
  GrossCommission: number;
  IsDeleted: Generated<number>;
  Loan: number;
  NetCommision: number;
  RCDF: number;
  ReleaseFrom: Date;
  ReleaseTo: Date;
  TaxAmount: number;
  WTaxAmount: number;
}

export interface TblCommissionMatrix {
  CommissionRateFrom: number;
  CommissionRateTo: number;
  CommMatrixCode: string;
  CommMatrixID: number;
  EffectivityDate: Date;
  HandsOffBroker: number;
  IsActive: number;
  LastUpdate: Date;
  UpdateBy: number;
}

export interface TblCommissionMatrixDtl {
  CommissionRate: number;
  CommMatrixCode: string;
  CommMatrixDtlID: number;
  Position: string;
}

export interface TblCommissionRelease {
  AdvanceCom: Generated<number>;
  CollectionRefNumber: Generated<string>;
  CommAmtVATEx: Generated<number>;
  CommCollectionDtlID: Generated<number>;
  CommissionStatus: Generated<string>;
  CommRate: number;
  CommReleaseDate: Date;
  CommReleaseNo: string;
  CommReleaseType: string;
  CommRelStatus: string;
  ComReleaseID: Generated<number>;
  DeductionNumber: Generated<string>;
  DeveloperTaxAmount: number;
  DeveloperTaxRate: number;
  InputVATAmt: Generated<number>;
  InputVATRate: Generated<number>;
  IsActive: Generated<number>;
  LastUpdate: Generated<Date>;
  LastUpdateBy: Generated<number>;
  NetCommission: number;
  PercentReleased: number;
  PreviousReleasedAmt: Generated<number>;
  ReleasedAmount: number;
  SalesTransCode: string;
}

export interface TblCommissionReleaseDtl {
  AdvCommission: Generated<number>;
  AgentID: Generated<number | null>;
  AgentName: Generated<string>;
  CADeduction: Generated<number>;
  CommissionBase: Generated<number>;
  CommissionDue: Generated<number>;
  CommissionRate: Generated<number>;
  CommissionStatus: Generated<string>;
  ComReleaseDtlID: Generated<number>;
  ComReleaseNo: Generated<string>;
  DeductionNumber: Generated<string>;
  DevInputVat: Generated<number>;
  DevWtax: Generated<number>;
  GrossComm: Generated<number>;
  Incentive: Generated<number>;
  InputVat: Generated<number>;
  LoanDeduction: Generated<number>;
  NetCommission: Generated<number>;
  OtherDeduction: Generated<number>;
  PositionCode: Generated<string>;
  PositionID: Generated<number | null>;
  PrevReleaseAmt: Generated<number>;
  VATExComm: Generated<number>;
  VatRate: Generated<number>;
  WtaxAmount: Generated<number>;
  WtaxRate: Generated<number>;
}

export interface TblCommReleaseSchedule {
  CommScheduleDtlID: number;
  DeveloperID: number;
  DPPercentPaid: number;
  NoMonthsPaid: number;
  PercentRelease: number;
}

export interface TblComReleaseType {
  ComReleaseTypeCode: string;
  ComReleaseTypeID: number;
  ComReleaseTypeName: string;
  IsActive: number;
  LastUpdate: Date;
  UpdateBy: number;
  WithDevelopersTax: number;
}

export interface TblDevCommRate {
  BRRate: number;
  CommissionRate: number;
  CommissionRateID: number;
  Description: string;
  DeveloperCode: string;
  SDRate: number;
  SPRate: number;
}

export interface TblDevelopers {
  Address: string;
  CommRate: number;
  ContactNumber: string;
  ContactPerson: string;
  DeveloperCode: string;
  DeveloperID: number;
  DeveloperName: string;
  LastUpdate: Date;
  PartialReleaseAmount: number;
  PartialReleaseType: number;
  Position: string;
  ReleaseSchedule: string;
  TaxIDNumber: string;
  UpdateBy: number;
  VATRate: number;
  WtaxRate: number;
}

export interface TblDistribution {
  Distribution: string;
  DistributionCode: string;
  DistributionID: number;
  IsActive: number;
  LastUpdate: Date;
  Level: number;
  PositionID: number;
  UpdateBy: number;
}

export interface TblDivision {
  DirectorID: number;
  Division: string;
  DivisionCode: string;
  DivisionID: number;
  IsActive: number;
  LastUpdate: Date;
  UpdateBy: number;
}

export interface TblImage {
  ContentType: string;
  CreatedAt: Date;
  FileContent: Buffer;
  FileExtension: string;
  Filename: string;
  FileSize: number;
  ImageID: Generated<number>;
}

export interface TblLogs {
  LogDate: Date;
  LogID: number;
  LogType: string;
  Particular: string;
  ReferenceNumber: string;
  UserID: number;
}

export interface TblMessages {
  IsRead: number;
  Message: string;
  MessageDestinationID: number;
  MessageID: number;
  MessageStamp: Date;
  UserOriginID: number;
}

export interface TblPosition {
  IsActive: number;
  LastUpdate: Date;
  Position: string;
  PositionCode: string;
  PositionID: number;
  UpdateBy: number;
}

export interface TblProjects {
  Address: string;
  ContactNumber: string;
  DeveloperID: number;
  IsLeadProject: number;
  LastUpdate: Date;
  ProjectCode: string;
  ProjectID: number;
  ProjectName: string;
  ProjectTypeID: number;
  SectorID: number;
  UpdateBy: number;
}

export interface TblProjectType {
  IsActive: number;
  LastUpdate: Date;
  ProjectTypeCode: string;
  ProjectTypeID: number;
  ProjectTypeName: string;
  UpdateBy: number;
}

export interface TblResetPasswordToken {
  CreatedAt: Generated<Date>;
  ResetPasswordTokenID: Generated<number>;
  Token: string;
  UserID: number;
  ValidUntil: Date;
}

export interface TblSalesBranch {
  BranchCode: string;
  BranchID: number;
  BranchName: string;
  HeadOffice: number;
  IsActive: number;
  LastUpdate: Date;
  UpdateBy: number;
}

export interface TblSalesDistribution {
  Distribution: string;
  DistributionCode: string;
  DistributionID: number;
  IsActive: number;
  LastUpdate: Date;
  Level: number;
  UpdateBy: number;
}

export interface TblSalesParameterDetail {
  PartialReleaseAmount: number;
  VendorID: number;
}

export interface TblSalesParameters {
  LeadProjectTax: number;
  NonLeadProjectTax: number;
  PartialCommRelease: number;
}

export interface TblSalesSector {
  LastUpdate: Date;
  SectorCode: string;
  SectorID: number;
  SectorName: string;
  UpdateBy: number;
}

export interface TblSalesTarget {
  SalesTargetID: number;
  TargetAmount: number;
  TargetEntity: string;
  TargetName: string;
  TargetNameID: number;
  TargetYear: number;
}

export interface TblSalesTrans {
  Block: string;
  BuyersAddress: string | null;
  BuyersContactNumber: string | null;
  BuyersName: string | null;
  BuyersOccupation: string | null;
  CommStatus: string | null;
  DateFiled: Date | null;
  DevCommType: string;
  DeveloperID: number | null;
  DivisionID: number | null;
  DownPayment: number;
  DPStartSchedule: Date | null;
  DPTerms: string;
  FinancingScheme: string;
  FloorArea: number;
  LastUpdate: Date;
  LastUpdateby: number;
  Lot: string;
  LotArea: number;
  MiscFee: number;
  MonthlyDP: number;
  NetTotalTCP: number;
  Phase: string;
  ProjectID: number | null;
  ProjectLocationID: number | null;
  ReservationDate: Date;
  SalesBranchID: number | null;
  SalesSectorID: number;
  SalesStatus: string;
  SalesTranCode: string;
  SalesTranID: Generated<number>;
  SellerName: string;
}

export interface TblSalesTransDtl {
  AgentID: number;
  AgentName: string | null;
  Commission: number;
  CommissionRate: number;
  PositionID: number;
  PositionName: string;
  SalesTranCode: string;
  SalesTransDtlID: Generated<number>;
  VATRate: number;
  WTaxRate: number;
}

export interface TblSMSOut {
  AgentCP: string;
  CreatedDate: Date;
  IsScheduled: number;
  IsSent: number;
  Message: string;
  ScheduledDate: Date | null;
  SentDate: Date | null;
  SMSID: number;
}

export interface TblSMSTemplate {
  LastUpdate: Date;
  SMSMessage: string;
  SMSTemplateID: number;
  SMSType: string;
  UpdateBy: number;
}

export interface TblTokens {
  CreatedAt: Generated<Date>;
  Token: string;
  TokenID: Generated<number>;
  UserID: number;
  ValidUntil: Date;
}

export interface TblTraining {
  IsActive: number;
  LastUpdate: Date;
  Training: string;
  TrainingCode: string;
  TrainingID: number;
  UpdateBy: number;
}

export interface TblUsers {
  BranchID: number;
  BranchName: string;
  EmpName: string;
  Password: string;
  Role: string;
  UserCode: string;
  UserID: number;
  UserName: string;
}

export interface TblUserSession {
  ExpiresAt: Date;
  SessionID: Generated<number>;
  SessionString: string;
  UserID: number;
}

export interface VwAgentCommisionReleaseSMS {
  AgentName: string;
  CA: number;
  CommissionStatus: string;
  ContactNumber: string | null;
  CPD: number;
  DeductionNumber: string;
  FirstName: string | null;
  LastName: string | null;
  Loan: number;
  NetCommision: number;
  RCDF: number;
}

export interface VwAgentCommissionLedger {
  "Assistance Fee": number | null;
  Broker: number | null;
  commreleaseno: string;
  GrossComm: number | null;
  InputVAT: number | null;
  Others: number | null;
  "Referral Fee": number | null;
  "Sales Associate": number | null;
  "Sales Director": number | null;
  "Sales Person": number | null;
  "Unit Manager": number | null;
  WtaxAmount: number | null;
}

export interface VwAgentCommissionLedgerReport {
  AF: number | null;
  Broker: number | null;
  BuyersName: string | null;
  CommReleaseDate: Date | null;
  commreleaseno: string;
  DeveloperTaxAmount: number | null;
  GrossComm: number | null;
  InputVAT: number | null;
  InputVATAmt: number | null;
  NetComm: number | null;
  NetTotalTCP: number | null;
  Others: number | null;
  PercentReleased: number | null;
  ProjectName: string | null;
  ReleasedAmount: number | null;
  ReservationDate: string | null;
  RF: number | null;
  SA: number | null;
  SD: number | null;
  SP: number | null;
  UM: number | null;
  WtaxAmount: number | null;
}

export interface VwAgents {
  Address: string | null;
  AddressEmergency: string | null;
  AgentCode: string | null;
  AgentID: number | null;
  AgentName: string | null;
  AgentTaxRate: number;
  AgentTaxRateName: string;
  Birthdate: Date | null;
  CivilStatus: string | null;
  ContactEmergency: string | null;
  ContactNumber: string | null;
  Division: string | null;
  DivisionCode: string | null;
  DivisionID: string | null;
  DSHUDNumber: string | null;
  FirstName: string | null;
  IsActive: number | null;
  LastName: string | null;
  LastUpdate: Date | null;
  MiddleName: string | null;
  PersonEmergency: string | null;
  Position: string | null;
  PositionID: number | null;
  PRCNumber: string | null;
  ReferredByID: number;
  ReferredCode: string | null;
  ReferredName: string | null;
  Sex: string | null;
  UpdateBy: number | null;
}

export interface VwCommCollectionReleasing {
  BuyerName: string;
  CollectionRefNumber: string;
  CommCollectionDtlID: number;
  CommRelRefNo: string;
  ContractPrice: number;
  DevCommType: string;
  DeveloperID: number;
  DeveloperName: string;
  Division: string;
  DivisionID: number;
  Property: string;
  ReleaseAmount: number;
  ReservationDate: Date;
  SalesNumber: string;
  SalesStatus: string;
  SalesTranID: number;
  WithSalesRecord: number;
}

export interface VwCommCollections {
  ARDeduction: number;
  CollectionAmount: number;
  CollectionDate: Date;
  CollectionRefNumber: string;
  CommCollectionID: number;
  DeveloperCV: string;
  DeveloperCVDate: Date;
  DeveloperID: number;
  DeveloperName: string;
  LastUpdate: Date;
  NetCollectionAmount: number;
  UpdateBy: number;
  WtaxDeduction: number;
}

export interface VwCommissionCollections {
  ACDeduction: number | null;
  AdvanceCommission: number | null;
  BuyerName: string | null;
  CollectionDate: Date;
  CollectionRefNumber: string | null;
  CollRef: string;
  CommCollectionDtlID: number | null;
  CommCollectionID: number;
  CommRate: number | null;
  CommRelRefNo: string | null;
  ContractPrice: number | null;
  DeveloperCV: string;
  DeveloperCVDate: Date;
  DeveloperID: number;
  DeveloperName: string | null;
  GrossAmount: number | null;
  Incentive: number | null;
  InputVAT: string | null;
  NetAmount: number | null;
  OtherDeduction: number | null;
  PartialReleaseAmount: number | null;
  PartialReleaseType: number | null;
  Property: string | null;
  ReleaseAmount: number | null;
  ReservationDate: Date | null;
  SalesNumber: string | null;
  VATRate: number | null;
  WithholdingTax: number | null;
  WithSalesRecord: number | null;
  WtaxRate: number | null;
}

export interface VwCommissionLedger {
  "ASSISTANCE FEE": number | null;
  BROKER: number | null;
  CommReleaseDate: Date;
  CommReleaseno: string;
  DeveloperTaxAmount: number;
  GrossComm: number;
  InputVat: number;
  InputVatAmt: number;
  NetComm: number;
  OTHERS: number | null;
  PercentReleased: number;
  "REFERRAL FEE": number | null;
  ReleasedAmount: number;
  "SALES ASSOCIATE": number | null;
  "SALES DIRECTOR": number | null;
  "SALES PERSON": number | null;
  "UNIT MANAGER": number | null;
  WtaxAmount: number;
}

export interface VwCommissionRelease {
  AdvanceCom: number;
  Block: string;
  BuyersName: string | null;
  CommAmtVATEx: number;
  CommRate: number;
  CommReleaseDate: Date;
  CommReleaseNo: string;
  CommReleaseType: string;
  CommRelStatus: string;
  ComReleaseID: number;
  DeveloperName: string | null;
  DeveloperTaxAmount: number;
  DeveloperTaxRate: number;
  InputVATAmt: number;
  InputVATRate: number;
  Lot: string;
  NetCommission: number;
  NetTotalTCP: number;
  PercentReleased: number;
  Phase: string;
  PreviousReleasedAmt: number;
  ProjectName: string | null;
  Property: string | null;
  ReleasedAmount: number;
  ReservationDate: string | null;
  SalesTransCode: string;
}

export interface VwCommissionReleaseDeductionReport {
  AdvCommission: number | null;
  AgentID: number | null;
  AgentName: string | null;
  Block: string;
  BuyersName: string | null;
  CA: number | null;
  CommAmtVATEx: number;
  CommDeductionDate: Date | null;
  CommissionRate: number | null;
  CommissionStatus: string | null;
  CommRate: number;
  CommReleaseDate: Date;
  CommReleaseNo: string;
  CommReleaseType: string;
  ComReleaseID: number;
  CPD: number | null;
  DeductionNumber: string | null;
  DeductionType: number | null;
  DevCommission: number;
  DeveloperName: string | null;
  DeveloperTaxAmount: number;
  DeveloperTaxRate: number | null;
  DevTaxAmount: number;
  Expr1: number | null;
  GrossCommission: number | null;
  Incentive: number | null;
  InputVat: number | null;
  InputVATAmt: number;
  Loan: number | null;
  LoanDeduction: number | null;
  Lot: string;
  NetCommision: number | null;
  NetCommission: number;
  NetTotalTCP: number;
  OtherDeduction: number | null;
  PartialReleaseAmount: number | null;
  PartialReleaseType: number | null;
  PercentReleased: number;
  Phase: string;
  PositionCode: string | null;
  PositionID: number | null;
  PrevReleaseAmt: number | null;
  ProjectName: string | null;
  Property: string | null;
  RCDF: number | null;
  ReleasedAmount: number;
  ReservationDate: string | null;
  SalesTransCode: string;
  TaxAmount: number | null;
  VatRate: number | null;
  WtaxAmount: number | null;
  WtaxRate: number | null;
}

export interface VwCommissionReleaseDetails {
  AdvCommission: number;
  AgentID: number | null;
  AgentName: string;
  CommissionRate: number;
  CommissionStatus: string;
  CommRate: number;
  CommReleaseDate: Date;
  CommReleaseNo: string;
  CommReleaseType: string;
  CommRelStatus: string;
  ComReleaseID: number;
  DeductionNumber: string;
  DeveloperTaxAmount: number;
  DeveloperTaxRate: number;
  GrossComm: number;
  Incentive: number;
  InputVat: number;
  InputVATAmt: number;
  IsActive: number;
  LastUpdate: Date;
  LastUpdateBy: number;
  LoanDeduction: number;
  NetComm: number;
  NetCommission: number;
  OtherDeduction: number;
  PercentReleased: number;
  PositionCode: string;
  PositionID: number | null;
  PrevReleaseAmt: number;
  ReleasedAmount: number;
  SalesTransCode: string;
  VatRate: number;
  WtaxAmount: number;
  WtaxRate: number;
}

export interface VwCommissionReleaseReport {
  AdvanceCom: number;
  AgentID: number | null;
  AgentName: string | null;
  BuyersName: string | null;
  CommAmtVATEx: number;
  CommissionBase: number | null;
  CommissionStatus: string | null;
  CommRate: number;
  CommReleaseDate: string | null;
  CommReleaseNo: string;
  CommReleaseType: string;
  CommRelStatus: string;
  ComReleaseDtlID: number | null;
  ComReleaseID: number;
  ContractPRice: number | null;
  DeductionNumber: string | null;
  DeveloperTaxAmount: number;
  DeveloperTaxRate: number;
  DevInputVat: number | null;
  DevWtax: number | null;
  DtlAdvCommission: number | null;
  DtlCADeduction: number | null;
  DtlCommissionBase: number | null;
  DtlCommissionRate: number | null;
  DtlCommissionTax: number;
  DtlGrossComm: number | null;
  DtlIncentive: number | null;
  DtlInputVat: number | null;
  DtlLoanDeduction: number | null;
  DtlNetCommission: number | null;
  DtlOtherDeduction: number | null;
  DtlPrevReleaseAmt: number | null;
  DtlWtaxAmount: number | null;
  GrossComm: number | null;
  InputVATAmt: number;
  InputVATRate: number;
  IsActive: number;
  LastUpdate: Date;
  LastUpdateBy: number;
  NetCommission: number;
  PercentReleased: number;
  PositionCode: string | null;
  PositionID: number | null;
  PreviousReleasedAmt: number;
  Property: string | null;
  ReleasedAmount: number;
  ReservationDate: string | null;
  SalesTransCode: string;
}

export interface VwDivisionDirector {
  AgentName: string | null;
  DirectorID: number;
  Division: string;
  DivisionID: number;
}

export interface VwDivisionSalesDash {
  CurrentMonth: number | null;
  CurrentMonthLastYear: number | null;
  Division: string;
  LastMonth: number | null;
}

export interface VwDivisionSalesTarget {
  CurrentMonth: number | null;
  CurrentYear: number | null;
  DivisionName: string | null;
  PercentMonth: number | null;
  PercentYear: number | null;
  SalesYear: number | null;
  TargetMonth: number | null;
  TargetYear: number;
}

export interface VwIncentives {
  AdditionalIncentive: number | null;
  AdditionalSalesIncentive: number | null;
  AdditionalSalesVolume: number | null;
  CashIncentiveCode: string;
  CashIncentiveDtlID: number | null;
  CashIncentiveID: number;
  Incentive: number | null;
  IncentiveType: string;
  IsActive: number;
  MinimumSales: number | null;
  PeriodFrom: Date;
  PeriodTo: Date;
  Position: string | null;
  SalesVolume: number | null;
}

export interface VwMessages {
  Destination: string | null;
  IsRead: number;
  Message: string;
  MessageDestinationID: number;
  MessageID: number;
  MessageStamp: Date;
  Origin: string | null;
  UserOriginID: number;
}

export interface VwMonthlySalesComparison {
  CurrentYear: number | null;
  LastYear: number | null;
  MNAME: string | null;
  mno: number | null;
}

export interface VwMonthlySalesComparisonDivision {
  CurrentYear: number | null;
  Division: string;
  LastYear: number | null;
  MNAME: string | null;
  mno: number | null;
}

export interface VwProjects {
  Address: string;
  ContactNumber: string;
  DeveloperID: number;
  DeveloperName: string | null;
  IsLeadProject: number;
  LastUpdate: Date;
  ProjectCode: string;
  ProjectID: number;
  ProjectName: string;
  ProjectTypeID: number;
  ProjectTypeName: string | null;
  SectorID: number;
  SectorName: string;
  UpdateBy: number;
}

export interface VwReferredBy {
  AgentCode: string;
  AgentID: number;
  Division: string;
  DivisionID: string | null;
  FirstName: string;
  LastName: string;
  MiddleName: string;
  Position: string;
  PositionID: number | null;
}

export interface VwReportPaidUp {
  agentid: number | null;
  AgentName: string;
  BuyersName: string | null;
  CommReleaseDate: Date;
  ComReleaseId: number;
  DeveloperName: string | null;
  Division: string;
  DivisionID: number | null;
  LastUpdate: Date;
  NetTotalTCP: number | null;
  PercentReleased: number;
  Position: string | null;
  PositionID: number | null;
  ProjectName: string | null;
  ReservationDate: Date | null;
  SalesTransCode: string;
}

export interface VwSalesMonth {
  CurrentMonth: number | null;
  CurrentMonthLastYear: number | null;
  LastMonth: number | null;
}

export interface VwSalesPersonCommission {
  agentid: number | null;
  AgentName: string;
  CommReleaseDate: Date;
  ComReleaseId: number;
  LastUpdate: Date;
  PercentReleased: number;
  SalesTransCode: string;
}

export interface VwSalesTrans {
  Block: string;
  BranchName: string | null;
  BuyersAddress: string | null;
  BuyersContactNumber: string | null;
  BuyersName: string | null;
  BuyersOccupation: string | null;
  CommStatus: string | null;
  DateFiled: Date | null;
  DevCommType: string;
  DeveloperID: number | null;
  DeveloperName: string | null;
  Division: string | null;
  DivisionID: number | null;
  DownPayment: number;
  DPStartSchedule: Date | null;
  DPTerms: string;
  FinancingScheme: string;
  FloorArea: number;
  LastUpdate: Date;
  LastUpdateby: number;
  Lot: string;
  LotArea: number;
  MiscFee: number;
  MonthlyDP: number;
  NetTotalTCP: number;
  Phase: string;
  ProjectID: number | null;
  ProjectLocationID: number | null;
  ProjectName: string | null;
  Property: string | null;
  ReservationDate: string | null;
  SalesBranchID: number | null;
  SalesSectorID: number;
  SalesStatus: string;
  SalesTranCode: string;
  SalesTranID: number;
  SectorName: string | null;
  SellerName: string;
}

export interface VwSalesTransactions {
  AgentID: number | null;
  AgentName: string | null;
  Block: string | null;
  BuyersAddress: string | null;
  BuyersContactNumber: string | null;
  BuyersName: string | null;
  BuyersOccupation: string | null;
  CommissionRate: number | null;
  DateFiled: Date | null;
  DevCommType: string | null;
  DeveloperID: number | null;
  DeveloperName: string | null;
  Division: string;
  DivisionID: number | null;
  DownPayment: number | null;
  DPStartSchedule: Date | null;
  DPTerms: string | null;
  Expr1: number | null;
  FinancingScheme: string | null;
  FloorArea: number | null;
  LastUpdate: Date | null;
  LastUpdateby: number | null;
  Lot: string | null;
  LotArea: number | null;
  MiscFee: number | null;
  MonthlyDP: number | null;
  NetTotalTCP: number | null;
  Phase: string | null;
  PositionName: string | null;
  ProjectID: number | null;
  ProjectLocationID: number | null;
  ProjectName: string | null;
  ReservationDate: Date | null;
  SalesBranchID: number | null;
  SalesStatus: string | null;
  SalesTranCode: string | null;
  SalesTranID: number | null;
  SalesTransDtlID: number | null;
}

export interface VwSalesTransAgentTaxRates {
  AgentID: number;
  AgentName: string | null;
  AgentTaxRate: number | null;
  AgentTaxRateID: number | null;
  Commission: number;
  CommissionRate: number;
  PositionID: number;
  PositionName: string;
  SalesTranCode: string;
  SalesTransDtlID: number;
  VATRATE: number;
  WtaxRate: number;
}

export interface VwUsers {
  BranchID: number;
  BranchName: string | null;
  EmpName: string;
  HeadOffice: number | null;
  Password: string;
  Role: string;
  UserCode: string;
  UserID: number;
  UserName: string;
}

export interface XTblClients {
  Address: string;
  Barangay: string;
  City: string;
  CivilStatus: string;
  ClientCode: string;
  ClientID: number;
  ContactNumber: string;
  FirstName: string;
  LastName: string;
  LastUpdate: Date;
  MiddleName: string;
  Occupation: string;
  Province: string;
  Sex: string;
  Street: string;
  UpdateBy: number;
}

export interface DB {
  database_firewall_rules: DatabaseFirewallRules;
  SalesTransTemp: SalesTransTemp;
  Tbl_AgentEducation: TblAgentEducation;
  Tbl_AgentPendingSales: TblAgentPendingSales;
  Tbl_AgentPendingSalesDtl: TblAgentPendingSalesDtl;
  Tbl_AgentReferral: TblAgentReferral;
  Tbl_AgentRegistration: TblAgentRegistration;
  Tbl_Agents: TblAgents;
  Tbl_AgentSession: TblAgentSession;
  Tbl_Agentsold: TblAgentsold;
  Tbl_AgentTaxRates: TblAgentTaxRates;
  Tbl_AgentUser: TblAgentUser;
  Tbl_AgentWorkExp: TblAgentWorkExp;
  tbl_BranchDivision: TblBranchDivision;
  Tbl_Broker: TblBroker;
  Tbl_Buyers: TblBuyers;
  tbl_CashIncentive: TblCashIncentive;
  tbl_CashIncentiveDtl: TblCashIncentiveDtl;
  Tbl_ChartOfAccounts: TblChartOfAccounts;
  Tbl_CommCollection: TblCommCollection;
  tbl_CommCollectionDtl: TblCommCollectionDtl;
  Tbl_CommDeductionDetail: TblCommDeductionDetail;
  Tbl_CommDeductionSummary: TblCommDeductionSummary;
  tbl_CommissionMatrix: TblCommissionMatrix;
  tbl_CommissionMatrixDtl: TblCommissionMatrixDtl;
  Tbl_CommissionRelease: TblCommissionRelease;
  tbl_CommissionReleaseDtl: TblCommissionReleaseDtl;
  tbl_CommReleaseSchedule: TblCommReleaseSchedule;
  Tbl_ComReleaseType: TblComReleaseType;
  Tbl_DevCommRate: TblDevCommRate;
  Tbl_Developers: TblDevelopers;
  Tbl_Distribution: TblDistribution;
  Tbl_Division: TblDivision;
  Tbl_Image: TblImage;
  Tbl_logs: TblLogs;
  tbl_Messages: TblMessages;
  Tbl_Position: TblPosition;
  Tbl_Projects: TblProjects;
  Tbl_ProjectType: TblProjectType;
  Tbl_ResetPasswordToken: TblResetPasswordToken;
  Tbl_SalesBranch: TblSalesBranch;
  tbl_SalesDistribution: TblSalesDistribution;
  Tbl_SalesParameterDetail: TblSalesParameterDetail;
  Tbl_SalesParameters: TblSalesParameters;
  Tbl_SalesSector: TblSalesSector;
  Tbl_SalesTarget: TblSalesTarget;
  Tbl_SalesTrans: TblSalesTrans;
  Tbl_SalesTransDtl: TblSalesTransDtl;
  tbl_SMSOut: TblSMSOut;
  Tbl_SMSTemplate: TblSMSTemplate;
  Tbl_Tokens: TblTokens;
  Tbl_Training: TblTraining;
  Tbl_Users: TblUsers;
  Tbl_UserSession: TblUserSession;
  vw_AgentCommisionReleaseSMS: VwAgentCommisionReleaseSMS;
  vw_AgentCommissionLedger: VwAgentCommissionLedger;
  vw_AgentCommissionLedgerReport: VwAgentCommissionLedgerReport;
  Vw_Agents: VwAgents;
  vw_CommCollectionReleasing: VwCommCollectionReleasing;
  vw_CommCollections: VwCommCollections;
  vw_CommissionCollections: VwCommissionCollections;
  vw_CommissionLedger: VwCommissionLedger;
  Vw_CommissionRelease: VwCommissionRelease;
  Vw_CommissionReleaseDeductionReport: VwCommissionReleaseDeductionReport;
  Vw_CommissionReleaseDetails: VwCommissionReleaseDetails;
  Vw_CommissionReleaseReport: VwCommissionReleaseReport;
  vw_DivisionDirector: VwDivisionDirector;
  vw_DivisionSalesDash: VwDivisionSalesDash;
  vw_DivisionSalesTarget: VwDivisionSalesTarget;
  vw_Incentives: VwIncentives;
  vw_Messages: VwMessages;
  vw_MonthlySalesComparison: VwMonthlySalesComparison;
  vw_MonthlySalesComparisonDivision: VwMonthlySalesComparisonDivision;
  vw_Projects: VwProjects;
  vw_ReferredBy: VwReferredBy;
  vw_ReportPaidUp: VwReportPaidUp;
  vw_SalesMonth: VwSalesMonth;
  vw_SalesPersonCommission: VwSalesPersonCommission;
  vw_SalesTrans: VwSalesTrans;
  Vw_SalesTransactions: VwSalesTransactions;
  vw_SalesTransAgentTaxRates: VwSalesTransAgentTaxRates;
  vw_Users: VwUsers;
  xTbl_Clients: XTblClients;
}
